#!/bin/bash

function addDNSdomain{
    clear
    # Define the filename
    filename='/usr/local/bin/domainlist'

    # Type the text that you want to append
    read -p "Enter domain name:" domain
    read -p "Enter host:" host
    read -p "Enter API Key:" apikey
    read -p "Enter API Secret:" apisecret
    # Check the new text is empty or not
    if [ "$newtext" != "" ]; then
        # Append the text by using '>>' symbol
        echo updatedns.sh $domain $host $apikey $apisecret >> $filename
    fi
}

function listDomains{
    clear
    tail --line=+5 /usr/local/bin/domainlist
}

function runddns-godaddy {
    clear
        read -n1 -p -e "Hello $(whoami)! Do you wish to: \n[1] Add a new Dyn-DNS configuration \nOR \n[2]View your current configured domains " runCommand

        case $runCommand in
            1) clear && addDNSdomain;;
            2) clear && listDomains;;
        esac
}

runddns-godaddy