#!/bin/bash

function addDNSdomain
{   clear
    # Define the filename
    filename='/usr/local/bin/domainlist'

    # Type the text that you want to append
    read -p "Enter domain name:" domain
    read -p "Enter host:" host
    read -p "Enter API Key:" apikey
    read -p "Enter API Secret:" apisecret
    # Append the text by using '>>' symbol
    echo /usr/local/bin/updatedns $domain $host $apikey $apisecret >> $filename
    
}

function listDomains
{   clear
    tail --line=+5 /usr/local/bin/domainlist
}

function runddns-godaddy
{   clear
        echo -e "Hello $(whoami)! Do you wish to: \n[1] Add a new Dyn-DNS configuration \n[2] View your current configured domains \n"
        read -n1 -p "1 or 2: " runCommand

        case $runCommand in
            1) clear && addDNSdomain;;
            2) clear && listDomains;;
        esac
}

runddns-godaddy