#!/bin/bash

function addDNSdomain
{   function manual
    {
        clear
        # Define the filename
        filename='/usr/local/bin/ddns/domainlist'

        # Type the text that you want to append
        read -p "Enter domain name:" domain
        read -p "Enter host:" host
        read -p "Enter API Key:" apikey
        read -p "Enter API Secret:" apisecret
        # Append the text by using '>>' symbol
        echo /usr/local/bin/ddns/updatedns $host $domain $apikey $apisecret >> $filename
    }
    function auto
    {
        clear
        # Define the filename
        filename='/usr/local/bin/ddns/domainlist'
        echo -e "What domain/API do you wish to use?"
        tail --line=+2 /usr/local/bin/ddns/.domainAPI
        read -p "Enter the # of the desired row: " domainNum
        #Define API domain line
        domainNumCor=$[$domainNum + 1]
        domainLine=$(sed -n $domainNumCor,$domainNumCor'p' /usr/local/bin/ddns/.domainAPI)
        read -p "Enter host:" host
        # Append the text by using '>>' symbol
        echo /usr/local/bin/ddns/updatedns $host $domainLine >> $filename
    }
    clear
        echo -e "Do you wish to manually configure the domain API or use the existing config file?"
        read -n1 -p "[m]Manually, [a]Use existing config file: " runCommand

        case $runCommand in
            m) clear && manual;;
            a) clear && auto;;

        esac
}

function listDomains
{   clear
    tail --line=+5 /usr/local/bin/ddns/domainlist
}

function confAPI
{   clear
    #Define API file
    APIfile='/usr/local/bin/ddns/.domainAPI'

    #Type the domain and API info you want to append
    read -p "Enter domain name:" domain
    read -p "Enter API Key:" apikey
    read -p "Enter API Secret:" apisecret
    #Append to API file
    echo $domain $apikey $apisecret >> $APIfile
}

function listAPI
{   clear
    tail --line=+2 /usr/local/bin/ddns/.domainAPI
}

function uninstall
{
    clear
    sudo rm -R /usr/local/bin/ddns
    crontab -l | grep -v '/usr/local/bin/ddns/domainlist' | crontab -
    sudo rm /usr/local/bin/ddns-godaddy
    exit
}

function confirm
{
    clear
    echo -e "Are you sure?\n"
    read -n1 -p "[Y]es or [N]o: " answ

    case $answ in
        Y) clear && uninstall;;
        N) clear && exit;;
    esac
}

function runddns-godaddy
{   clear
        echo -e "Hello $(whoami)! Do you wish to: \n[1] Add a new Dyn-DNS configuration \n[2] Configure new domain API \n[3] View your current configured hosts \n[4] View your current domain APIs \n[5] Uninstall"
        read -n1 -p "1, 2, 3: " runCommand

        case $runCommand in
            1) clear && addDNSdomain;;
            2) clear && confAPI;;
            3) clear && listDomains;;
            4) clear && listAPI;;
            5) clear && confirm;;
        esac
}

runddns-godaddy